### PR TITLE
Services Page w/ fixture data

### PR DESCRIPTION
**Pull request by thebritican**
@zendesk/volunteer 

Please style. make pretty ✨ 💖 

This is just some components and some fixture data taken from our firebase schema.

Have fun!

### CODE REVIEW

**Comment by thebritican** [comment]
@zendesk/volunteer this should be ready to merge now, take it for a test 🚗 plz and maybe a 👍 ??

**Comment by thebritican** [comment]
image

**Comment by thebritican** [comment]
image

**Comment by cpovey** [comment]
👍

**Pull request merged**
