### PR TITLE
admin pages

### PR DESCRIPTION
**Pull request by craig-day**
Making a PR with this to see what it looks like. 

**Main admin page**

**Edit organization page**

TODO after this PR:

1. Use the new firebase client to create/update items
2. Figure out the icons
3. Make all of the create/edit pages actual separate pages, not just components rendered in the same page
4. Make sure everything is auth'd

/cc @roseleaf @thebritican @adam-hart

### CODE REVIEW

**Comment by craig-day** [comment]
Okay, rebased and everything is working.  Also switched the fetching to use the new firebase stuffs, will have to refactor the updating later. 

/cc @zendesk/volunteer review plz

**Comment by craig-day** [comment]
I'm not sure what all of the icons foobar is, but I'm going to leave it as is...

**Comment by thebritican** [comment]
can you screen shot real quick? otherwise I'm sure it's a fine place to work from

**Comment by craig-day** [comment]
added screenshots to the description

**Comment by craig-day** [comment]
As I was rebasing and refactoring some things, I changed most of what I thought was a blocker, so I give this my stamp of approval. 

:+1:

**Pull request merged**
