### PR TITLE
[ES-LINT] Consistent code style 💎 

### PR DESCRIPTION
**Pull request by thebritican**
After a decisive vote: goodbye semis
Hello dangling commas

### CODE REVIEW

**Comment by jden** [comment]
✨

**Comment by jden** [comment]
just as an anecdote, and certainly not to interlope, but projects such as radar and inbox are using http://standardjs.com/

**Comment by thebritican** [comment]
@jden good to note! right now it's just Airbnb default with dangling commas and no semis.

**Comment by adam-hart** [comment]
:nike: just do it 👍

**Pull request merged**
