### PR TITLE
remove flex from homepage and layout

### PR DESCRIPTION
**Pull request by craig-day**
remove flex from the layout and the homepage. 

/cc @zendesk/volunteer

### CODE REVIEW

**Comment by roseleaf** [comment]
was this tested on the metro phones' browsers?

**Comment by craig-day** [comment]
not yet, but it certainly won't make it worse :D.  Someone should deploy this branch and verify before merging though.

**Comment by roseleaf** [comment]
SOMEONE! :D

**Comment by craig-day** [comment]
Hey, I don't have the poopy phones. Thats all you!

**Pull request closed without merging**
