### PR TITLE
More Feedback Page

### PR DESCRIPTION
**Pull request by mikehuston**
Improvements to feedback page:
 * make feedback link on home page actually link to feedback page
 * basic form styling
 * basic form validations

@zendesk/volunteer

### CODE REVIEW

**Comment by craig-day** [comment]
screenshot? :D

**Comment by mikehuston** [comment]
What it looks like in master branch / http://www.link-sf.com/#/feedback:
screen shot 2016-08-31 at 4 48 25 pm

What is looks like after these changes:
screen shot 2016-08-31 at 4 48 34 pm

Validation of required input field in Chrome:
screen shot 2016-08-31 at 4 51 00 pm

Validation of missing input field in Safari / other browsers:
screen shot 2016-08-31 at 4 49 11 pm

**Comment by craig-day** [comment]
ooooo so fancy! :+1:

**Comment by thebritican** [comment]
👍 sweet as man

**Comment by roseleaf** [comment]
Looks awesome!!!! 🎉 

We should really start testing in older mobile browsers as well. I have a couple test devices we can validate on this week. As great as chrome and safari are for developing, most of our target demographic won't have either

**Comment by mikehuston** [comment]
@roseleaf, yes great idea!

**Pull request merged**
