### PR TITLE
Add icons

### PR DESCRIPTION
**Pull request by adam-hart**
I still can't get the fonts to fully load, but this will put them in webpack. [www.copyshrug.com](copyshrug.com) 

selfie-0

### CODE REVIEW

**Comment by jden** [comment]
idk if this pr has a sufficient number of selfies

**Comment by craig-day** [comment]
you look like a zombie.  your face is all dark and purpley and crap.

**Comment by craig-day** [comment]
you should also add 

```
branches: 
  only: :master
```

to the travis yaml file so there aren't two builds for every PR

**Comment by thebritican** [comment]
👍

selfie-2
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by thebritican** [comment]
selfie-1
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by thebritican** [comment]
wurk wurk wurk wurk wurk 👍

**Pull request merged**
